### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by codingjeff01** [jeffersonrj14/jeffersonrj14#4]
Trying to do the same thing as this repo, but it won't let me. Got denied by github-actions, maybe you could help me with it. Thank you. here's the log

```bash
remote: Permission to codingjeff01/auto-update.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/codingjeff01/auto-update/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by jeffersonrj14** [comment]
Regarding your issue, make sure you have enabled the Workflow permissions.
Here's how to do it:
1. Head to settings
2. Go to Actions > General
3. Scroll down and see Workflow permissions
       - Ensure that `Read and write permissions` is selected.
       - Also, select `Allow GitHub Actions to create and approve pull requests`

Let me know if this works.

**Comment by codingjeff01** [comment]
Thank you so much, I have other questions. How do you add the api secrets?

**Comment by jeffersonrj14** [comment]
Since this repo uses GitHub Actions:

1. Go to Settings.
2. Navigate to Secrets and Variables > Actions
3. Press `New repository secret`
4. Input the Name `WEATHER_API_TOKEN` and put your api key on secret

If you have any further queries or need additional assistance, feel free to ask here.

**Comment by codingjeff01** [comment]
Thank you so much! I've resolved all the issues I was facing. Thank you for your assistance. I will close these issues now, as I haven't encountered any errors or problems.
